package exception_handling;

public class TryCatchTest2 {

}
